# Generated by Django 4.2 on 2023-06-11 13:35

from django.db import migrations
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', orders.models.UserManager()),
            ],
        ),
    ]
