# Generated by Django 4.2 on 2023-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinfo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Внешний ИД'),
            preserve_default=False,
        ),
    ]
