# Generated by Django 4.2 on 2023-06-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_productparameter_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
