# Generated by Django 4.2 on 2023-06-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='category',
        ),
    ]
