# Generated by Django 4.2 on 2023-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
